ecommerceproject/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),    
    # path('myview/', views.myview, name='myview'),
]
# print("myapp/urls.py: urlpatterns =", urlpatterns)

ecommerceproject/ecommerceproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('searchapp/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# print(urlpatterns)

ecommerceproject/search_app/urls.py
from django.urls import path 
from. import views

app_name='search_app'

urlpatterns=[
    path('', views.SearchResult, name='SearchResult'),
]

ecommerceproject/shop/urls.py
from django.urls import path
from.import views
app_name='shop'

urlpatterns = [

    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.ProDetail,name='prodCatdetail')

]

ecommerceproject/cart/models.py
from django.db import models
from shop.models import Product,Category
# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250,blank=True)
    date_added = models.DateField(auto_now_add=True)


    class Meta:
        db_table = 'cart'
        ordering = ['date_added']


    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'Cartitem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommerceproject/search_app/models.py
from django.db import models

# Create your models here.

ecommerceproject/shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('shop:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)
    
class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    def get_url(self):
        return reverse('shop:prodCatdetail',args=[self.category.slug,self.slug])

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'

    def __str__(self):
        return '{}'.format(self.name)

ecommerceproject/cart/views.py
from django.shortcuts import render,redirect
from shop.models import Product,Category
from . models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist


def _cart_id(request):
    # print("cart_id view called with p")
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request,product_id):
    # print("add_cart view called with product_id:", product_id)

    product = Product.objects.get(id = product_id)

    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save() 

    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        cart_item.quantity += 1
        cart_item.save()

    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product = product,
            quantity = 1,
            cart = cart
        )
        cart_item.save()
    # print("add_cart view executed successfully")
    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart = Cart.objects.get(cart_id= _cart_id(request))
        cart_items = CartItem.objects.filter(cart = cart,active = True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items = cart_items,total = total,counter = counter))
# def myview(request):
#     context = {
#         'total': 0,
#         'counter': 0,
#         'cart_items': None,
#     }

#     response = render(request, 'cart.html', context)
#     return response

ecommerceproject/search_app/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q

def SearchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query =  request.GET.get('q')
        print("Query:", query)
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request, 'search.html', {'query': query, 'products': products})

ecommerceproject/shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import Category, Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage

def allProdCat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
        
        categories = Category.objects.all()
    paginator=Paginator(products_list,8)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)

    context = {'category': c_page, 'products': products, 'categories': categories}
    return render(request, "category.html", context)

def ProDetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Product.DoesNotExist:
        raise Http404("Product not found")
    
    return render(request, 'product.html', {'product': product})

ecommerceproject/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="{% static 'shop/css/custom_css.css' %}">

    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body style="background-color: rgb(234, 234, 234);">
<div>
    {% include 'header.html' %}
    <br>
    <br>
    <br>
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    Cart Items
{% endblock %}
{% block title %}
Cart
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 style="color: red;">Your Cart is empty</h1><br>
        <p class = "text-center"><a href="{%url 'shop:allProdcat' %}">Continue shopping</a></p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <h1 class="text-center my_title">
            Your cart
        </h1>
        <br>
    </div>
    <div class="row mx-auto">  
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_cart_table">
                <thead class="my_cart_table_title">
                    <tr>
                        <th colspan="5">
                            your items
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for cart_item in cart_items %}
                    <tr>
                        <td>
                            <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="product image"></a>
                        </td>
                        <td class="text-lef">
                            {{cart_item.product.name}}
                            <br>
                            name : {{cart_item_product.id}}
                            <br>
                            Price : {{cart_item.product.price}}
                            <br>
                            Qty : {{cart_item.quantity}} x {{cart_item}}
                        </td>
                        <td>
                            Rs - {{cart_item.sub_total}}
                        </td>
                        {% if cart_item.quantity < cart_item.product.stock %}
                        <td>
                            <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-plus"></i></a> 
                            &nbsp;<a href="" class="cutom_a"><i class="fa-solid fa-minus"></i></a>
                            &nbsp;<a href="" class="cutom_icon"><i class="fa-solid fa-trash"></i>></i></a>
                        </td>
                        {% else %}
                        <td>
                            <td>
                                &nbsp;<a href="" class="cutom_a"><i class="fa-solid fa-minus"></i></a>
                                &nbsp;<a href="" class="cutom_icon"><i class="fa-solid fa-trash"></i>></i></a>
                            </td>
                        </td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>

    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="my_cart_table">
            <thead class="my_custom_thread">
                <tr>
                    <th>
                        Checkout
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        Please review your shopping cart items before prroceeding payments.
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'shop:allProdCat' %}" class="btn btn-secondary btn-block my_cart_table_button">Continue shopping</a>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

<style>
.my_cart_table{
    min-width:400px;
    font-size: 14px;
}

.my_cart_table_title{
    font-weight: normal;
    background-color: cyan;
    text-transform: uppercase;
    letter-spacing: .2em;
}
.custom_a
{
    text-decoration: none;
    margin-top: 5px;
}

</style>

ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        Welcome to ____
    
    {% endif %}
{% endblock %}

<!-- title -->

{% block title %}
{% if category %}
    {{ category.name }} -  abc
{% else %}
    Welcome to title

{% endif %}
{% endblock %}

<!-- contents -->

{% block content %}
{% if category %}

    <div>
        <div>
            <p><a href="{% url 'shop:allProdCat' %}">Our Product Collections"</a></p>

        </div>
    </div>
    {% endif %}
        <div>
            {% if category %}
                <img src="{{category.image.url}}" alt="{{category.name}}"  style="max-width: 200px; max-height: 200px;">
        </div>
            <br>
        <div>
            <h1>{{category.name}}</h1>
            <p>{{category.description}}</p>
        </div>
            {% else %}
            <div id="carouselExample" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{% static 'img/banner2.png' %}" class="d-block w-100" alt="Banner 1">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'img/banner3.png' %}" class="d-block w-100" alt="Banner 2">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExample" role="button" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExample" role="button" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </a>
            </div>
             
        {% endif %}

<div class="container">
  <div class="row">
    {% for category in categories %}
    <div class="col-sm-4">
      <div class="card my-card">
        <img src="{{ category.image.url }}" class="card-img-top my-card-img" alt="{{ category.name }}">
        <div class="card-body my-card-body">
          <h5 class="card-title my-card-title">{{ category.name }}</h5>
          <a href="{{product.get_url}}" class="btn btn-outline-light my-card-btn">Shop Now</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
<br>
<br>
<div>
<img src="{% static 'img/bannersmall2.png' %}"  alt="Banner 1" style="height: 100%; width: 1320px; margin-left: 120px;">

</div>
<div class="procontainer">
    <div class="row pro-row">
        {% for product in products.object_list %}
        <div class="col-sm-3">
            <div class="card pro-card">
                <a href="{{product.get_url}}"><img src="{{ product.image.url }}" alt="{{ product.name }}" class="card-img-top1"></a>
                <div class="card-body">
                    <h5 class="card-title">{{product.name|truncatewords:5}}</h5>
                    <p class="card-text">{{product.description|truncatewords:10}}</p>
                    <p class="card-text">Rs-{{product.price}}/-</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}
            <hr>
            <div class="text-center">
                {% for pg in products.paginator.page_range %}
                    <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %}active{% endif %}">{{pg}}</a>
                {% endfor %}
            </div>
        {% endif %}
    </div>
    
    <br>
</div>




<style>

.container {
    padding: 0 80px;
}

.row {
    margin: 0;
}

.col-sm-4 {
    padding: 0;
}

.my-card {
    position: relative;
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 300px;
    height: 400px;
    margin: 40px 40px;
}



.my-card-img {
    width: 100%;
    height: auto;
}

.my-card-body {
    position: absolute;
    bottom: 30px;
    left: 0;
    right: 0;
    height: 100px;
    display: flex;
    flex-direction: column;
    align-items: center;
}
.my-card-title {
    text-align:center;
    width: 100%;
    color: white;
}

.pro-card{
    position: relative;
    display: flex;
    align-items: center;
    width: 200px;
    height: 450px;
    margin: 40px 40px;
}
.pro-row{
    margin: 0;
}
.procontainer {
    padding: 0 80px;
}

.pro-row {
    margin: 0;
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
}

.col-sm-3 {
    padding: 0;
    margin-bottom: 20px; 
    flex: 0 0 calc(25% - 20px); 
}

.pro-card {
    position: relative;
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 300px;
    height: 425px;
}

.card-img-top1 {
    max-width: 170px;
    height: 170px;
}


</style>

{% endblock %}

ecommerceproject/templates/footer.html
<footer>
    <div class="footer-container">
        <div class="footer-section">
            <h4>Explore Tawa</h4>
            <ul>
                <li><a href="#">Sneakers</a></li>
                <li><a href="#">Sports</a></li>
                <li><a href="#">Casuals</a></li>
                <li><a href="#">Formals</a></li>
                <li><a href="#">Slippers</a></li>
                <li><a href="#">Flip-flops</a></li>
                <li><a href="#">Safety Shoes</a></li>
            </ul>
        </div>
        <div class="footer-section">
            <h4>Shop Clothing</h4>
            <ul>
                <li><a href="#">Shirts</a></li>
                <li><a href="#">Pants</a></li>
                <li><a href="#">Innerwear</a></li>
            </ul>
        </div>
        <div class="footer-section">
            <h4>Shop Accessories</h4>
            <ul>
                <li><a href="#">Bags</a></li>
                <li><a href="#">Belts</a></li>
                <li><a href="#">Wallets</a></li>
            </ul>
        </div>
        <div class="footer-section">
            <h4>Contact Us</h4>
            <ul>
                <li>Phone: +1234567890</li>
                <li>Email: info@tawa.com</li>
            </ul>
        </div>

    </div>

    <!-- Always keep exploring more! -->
    <div class="footer-section">
        <form action="#" method="post">
            <label for="email">Always keep exploring more!</label><br/>
            <input type="email" id="email" name="email" placeholder="Enter your email"><br/>
            <input type="submit" value="Subscribe">
        </form>

    </div>

    <!-- Social Media -->
    <div class="footer-section">
        Follow us on social media:<br/>
        Twitter | Facebook | Instagram
    </div>

    <!-- Copy right -->
    <div class="copy-right">
        © 2023 TAWA . All rights reserved.
    </div>

</footer>

<style>

footer {
    background-color: black;
    color: white;
    padding: 30px 0;
}

.footer-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    max-width: 1200px;
    margin: 0 auto;
}

.footer-section {
    flex-basis: calc(33.33% - 30px);
    margin-bottom: 30px;
}

.footer-section h4 {
    margin-bottom: 15px;
}

.footer-section ul {
    list-style: none;
    margin: 0;
    padding: 0;
}

.footer-section li {
    margin-bottom: 10px;
}

.footer-section a {
    color: white;
    text-decoration: none;
}

.footer-section a:hover {
    text-decoration: underline;
}

.copy-right {
    text-align: center;
    margin-top: 30px;
}

@media (max-width: 767px) {
    .footer-container {
        flex-direction: column;
        align-items: center;
    }

    .footer-section {
        flex-basis: auto;
        text-align:center;
        margin-bottom: 30px;
    }
}

ecommerceproject/templates/header.html
{% load static %}

<header style="background-color: black; display: flex; align-items: center; justify-content: space-between;">
    <div style="display: flex; align-items: center; padding-left: 80px;">
        <a href="{% url 'shop:allProdCat' %}">
            <img src="{% static 'img/logo2.1.png' %}" alt="logoimage" style="max-width: 100px; max-height: 100px;">
        </a>
        <nav>
            <ul style="list-style: none; display: flex; align-items: center;">
                <li style="margin-right: 20px;"><a href="{% url 'shop:allProdCat' %}" style="color: white; text-decoration: none;">Home</a></li>
                <li class="dropdown" style="margin-right: 20px;">
                    <a href="{% url 'shop:allProdCat' %}" style="color: white; text-decoration: none;">Collections</a>
                    <ul class="dropdown-menu" style="background-color: black; display: none;">
                        <li><a href="{% url 'shop:allProdCat' %}" style="color:white;">All Products</a></li>
                        {% for cat in links %}
                        <li><a href="{% url 'shop:products_by_category' cat.slug %}" style="color:white;">{{ cat.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li style="margin-right: 20px;"><a href="#" style="color: white; text-decoration: none;">About Us</a></li>
                <li style="margin-right: 20px;"><a href="#" style="color: white; text-decoration: none;">Sales</a></li>
            </ul>
        </nav>
    </div>
    <div style="padding-right: 80px; margin-bottom: 12px;">
        <form method="get" class="d-flex" action="{% url 'search_app:SearchResult' %}">
            {% csrf_token %}
            <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search" style="height: 35px;">
            <button type="submit" class="button1">Search</button>
        </form>
    </div>
</header>

<script>
    document.querySelector('form').addEventListener('submit', function(event) {
        event.preventDefault();
        var searchTerm = document.querySelector('input[type=search]').value;
    });

    document.querySelector('.dropdown > a').addEventListener('click', function(event) {
        event.preventDefault();
        var dropdownMenu = document.querySelector('.dropdown-menu');
        if (dropdownMenu.style.display === 'none') {
            dropdownMenu.style.display = 'block';
        } else {
            dropdownMenu.style.display = 'none';
        }
    });

    var header = document.querySelector('header');

    var prevScrollpos = window.pageYOffset;

    window.addEventListener('scroll', function() {
        var currentScrollPos = window.pageYOffset;

        if (prevScrollpos > currentScrollPos) {
            header.style.top = "0";
        } else {
            header.style.top = "-65px";
        }

        // Update the previous scroll position
        prevScrollpos = currentScrollPos;
    });
</script>
<style>
.dropdown-menu a {
    text-decoration: none;
}

.dropdown-menu {
    background-color: white;
}

header {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    z-index: 9999;
    transition: top 0.3s ease-in-out;
    /* margin-bottom: 50px; */
}
.button1 {
    background-color: black;
    color: #f6f6f6;
    border-style: solid;
    border-radius: 10%;
    border-color: #f6f6f6;
    height: 35px;
  transition-duration: 0.4s;
  text-align: center;
}

.button1:hover {
  background-color: #f6f6f6; /* Green */
  color: rgb(0, 0, 0);
}

</style>

ecommerceproject/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:allProdCat' %}">Home</a>
        </li>
        <li class="nav-item">
          <div class="category-links">
              {% for cat in links %}
              <a class="nav-link" href="{% url 'shop:products_by_category' cat.slug %}">{{cat.name}}</a>
              {% endfor %}
          </div>
      </li>
      
        
      </ul>
    </div>
  </div>
</nav>
<style>
  .category-links {
    display: flex;
}

.category-links a {
    margin-right: 10px;
}

</style>

ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

        {{ product.description|truncatewords:155 }}
    

{% endblock %}

<!-- title -->

{% block title %}
{% if category %}
    {{ product.name }} -  abc

{% endif %}
{% endblock %}

<!-- contents -->

{% block content %}
<!-- {% debug %} -->
<div>
    <div>
        <p><a href="{% url 'shop:allProdCat' %}" class="custom-link">Home</a>|<a href="{{product.category.get_url}}" class="custom-link">{{product.category}}</a>|{{product.name}}</p>
    </div>
</div>
<br>
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <div>
                <img src="{{ product.image.url }}" alt="{{ product.name }}" style="max-width: 450px; max-height: 650px;">
            </div>
        </div>
        <div class="col-sm-6">
            <h1>{{product.name}}</h1>
            
            <p>{{product.description}}</p>
            <br>
            <li><i>100% Original Products</li>
            <li>Pay on delivery might be available</li>
            <li>Easy 14 days returns and exchanges</li>
            <li>Try & Buy might be available</i></li> 
            <br>
            <br>
            <br>
            <p class="price"><strong>Rs - </strong><span style="color:orange;">{{product.price}}/-</span></p>

            <br>

            {% if product.stock <= 0 %}
            <p><b>Out Of Stock</b></p>
            {% else %}
            <a href="{% url 'cart:add_cart' product.id %}" class="btn btn-dark"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
            {% endif %}
        </div>
    </div>
</div>

<style>

.container {
    padding: 30px 0;
}

    a.custom-link {
        text-decoration: none;
        color: black;
        font-weight: bold;
        background-color: rgb(172, 172, 172);
    }
    
</style>
</style>

{% endblock %}

ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    We have variety of products
{% endblock %}
{% block title %}
Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for : <b>"{{query}}"</b></p>
</div>
<div class="procontainer">
    <div class="row pro-row">
        {% for product in products %}
        <div class="col-sm-3">
            <div class="card pro-card">
                <a href="{{product.get_url}}"><img src="{{ product.image.url }}" alt="{{ product.name }}" class="card-img-top1"></a>
                <div class="card-body">
                    <h5 class="card-title">{{product.name|truncatewords:5}}</h5>
                    <p class="card-text">{{product.description|truncatewords:10}}</p>
                    <p class="card-text">Rs-{{product.price}}/-</p>
                </div>
            </div>
        </div>
    {% empty %}
    <div class="row mx-auto">
        <p class="text-center my_search_text">0 results found</p>
    </div>
    {% endfor %}
</div>


<style>
    .my_search_text{
        padding-top: 20px;
    }
</style>
{% endblock %}